# Generated by Django 5.1.1 on 2024-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_user_accountmodel_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='confirmationcodesmodel',
            name='unique_code_per_user',
        ),
        migrations.RemoveField(
            model_name='confirmationcodesmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='confirmationcodesmodel',
            name='email',
            field=models.EmailField(default='helloworld@gmail.com', max_length=254),
        ),
        migrations.AddConstraint(
            model_name='confirmationcodesmodel',
            constraint=models.UniqueConstraint(fields=('code', 'email'), name='unique_code_per_email'),
        ),
    ]
