# Generated by Django 5.1.1 on 2024-10-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_confirmationcodesmodel_unique_code_per_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='profile_picture',
            field=models.ImageField(default='default/img.png', upload_to='profile_pictures/'),
        ),
    ]
